/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:8fb7d05f-ded9-42d3-a5bd-5839299af9ef",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_XEyTV05vy",
    "aws_user_pools_web_client_id": "7b0hb0rrduar1635miqhmi1hac",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cmluc7hcfbeqjah2xctmqn6k2u.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
